on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: deploy

jobs:
  deploy:
    if: "contains(github.event.head_commit.message, 'deploy app')"
    runs-on: macOS-latest
    timeout-minutes: 60
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.PRIVATE_ACTIONS_PAT }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rsconnect"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: shinyapps credentials
        run: |
          print("here")
          rsconnect::setAccountInfo(name='poissonconsulting', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})
          rsconnect::deployApp(appName = 'shinybugtest')
        shell: Rscript {0}
